version: "3.7"

services:
  eventstore.db:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=false
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1113:1113"
      - "2113:2113"
    restart: always
    
  eventstore.db.tests:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=false
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1114:1113"
      - "2114:2113"
    restart: always
      
  postgres.db.sales:
    image: postgres
    ports: 
      - 5438:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_Sales
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SALES}

  postgres.db.sales.tests:
    image: postgres
    ports: 
      - 5440:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_SalesTests
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SALES}

  postgres.db.billing:
    image: postgres
    ports: 
      - 5439:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_Billing
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BILLING}

  postgres.db.billing.tests:
    image: postgres
    ports: 
      - 5441:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_BillingTests
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BILLING}   

  postgres.db.catalog:
    image: postgres
    ports: 
      - 5442:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_Catalog
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_CATALOG}

  postgres.db.catalog.tests:
    image: postgres
    ports: 
      - 5443:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_CatalogTests
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_CATALOG}

  postgres.db.process_manager:
    image: postgres
    ports: 
      - 5444:5432
    restart: always
    volumes:
      - ./quartz_tables_postgres.sql:/docker-entrypoint-initdb.d/quartz_tables_postgres.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_ProcessManager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROCESS_MANAGER}

  postgres.db.process_manager.tests:
    image: postgres
    ports: 
      - 5445:5432
    restart: always
    volumes:
      - ./quartz_tables_postgres.sql:/docker-entrypoint-initdb.d/quartz_tables_postgres.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_ProcessManagerTests
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROCESS_MANAGER}
  postgres.db.identity:
    image: postgres
    ports: 
      - 5446:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_Identity
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_IDENTITY}

  postgres.db.identity.tests:
    image: postgres
    ports: 
      - 5447:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_IdentityTests
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_IDENTITY}