version: "3.7"

services:
  eventstore.db:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=false
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
      
  postgres.db.sales:
    image: postgres
    ports: 
      - 5438:5432
    restart: always
    volumes:
    - ./quartz_tables_postgres.sql:/docker-entrypoint-initdb.d/quartz_tables_postgres.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_Sales
      POSTGRES_PASSWORD: 0k6aamsucNq57XV7aOHC
      
  postgres.db.billing:
    image: postgres
    ports: 
      - 5439:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: VShop_Billing
      POSTGRES_PASSWORD: 46ftZwvHwkStZzzQtz6g