// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Modules/ProcessManager/_schemas/order_placed_domain_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VShop.Modules.ProcessManager.Infrastructure.Messages.Events {

  /// <summary>Holder for reflection information generated from Modules/ProcessManager/_schemas/order_placed_domain_event.proto</summary>
  internal static partial class OrderPlacedDomainEventReflection {

    #region Descriptor
    /// <summary>File descriptor for Modules/ProcessManager/_schemas/order_placed_domain_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderPlacedDomainEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj9Nb2R1bGVzL1Byb2Nlc3NNYW5hZ2VyL19zY2hlbWFzL29yZGVyX3BsYWNl",
            "ZF9kb21haW5fZXZlbnQucHJvdG8aPFNoYXJlZEtlcm5lbC9TaGFyZWRLZXJu",
            "ZWwuSW5mcmFzdHJ1Y3R1cmUvX3NjaGVtYXMvdXVpZC5wcm90bxoXZ29vZ2xl",
            "L3R5cGUvbW9uZXkucHJvdG8i5QIKFk9yZGVyUGxhY2VkRG9tYWluRXZlbnQS",
            "FwoIb3JkZXJfaWQYASABKAsyBS5VdWlkEikKDWRlbGl2ZXJ5X2Nvc3QYAiAB",
            "KAsyEi5nb29nbGUudHlwZS5Nb25leRIZChFjdXN0b21lcl9kaXNjb3VudBgD",
            "IAEoBRIaCgtjdXN0b21lcl9pZBgEIAEoCzIFLlV1aWQSEgoKZmlyc3RfbmFt",
            "ZRgFIAEoCRITCgttaWRkbGVfbmFtZRgGIAEoCRIRCglsYXN0X25hbWUYByAB",
            "KAkSFQoNZW1haWxfYWRkcmVzcxgIIAEoCRIUCgxwaG9uZV9udW1iZXIYCSAB",
            "KAkSDAoEY2l0eRgKIAEoCRIUCgxjb3VudHJ5X2NvZGUYCyABKAkSEwoLcG9z",
            "dGFsX2NvZGUYDCABKAkSFgoOc3RhdGVfcHJvdmluY2UYDSABKAkSFgoOc3Ry",
            "ZWV0X2FkZHJlc3MYDiABKAlCPqoCO1ZTaG9wLk1vZHVsZXMuUHJvY2Vzc01h",
            "bmFnZXIuSW5mcmFzdHJ1Y3R1cmUuTWVzc2FnZXMuRXZlbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VShop.SharedKernel.Infrastructure.Types.UuidReflection.Descriptor, global::Google.Type.MoneyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VShop.Modules.ProcessManager.Infrastructure.Messages.Events.OrderPlacedDomainEvent), global::VShop.Modules.ProcessManager.Infrastructure.Messages.Events.OrderPlacedDomainEvent.Parser, new[]{ "OrderId", "DeliveryCost", "CustomerDiscount", "CustomerId", "FirstName", "MiddleName", "LastName", "EmailAddress", "PhoneNumber", "City", "CountryCode", "PostalCode", "StateProvince", "StreetAddress" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class OrderPlacedDomainEvent : pb::IMessage<OrderPlacedDomainEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderPlacedDomainEvent> _parser = new pb::MessageParser<OrderPlacedDomainEvent>(() => new OrderPlacedDomainEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderPlacedDomainEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VShop.Modules.ProcessManager.Infrastructure.Messages.Events.OrderPlacedDomainEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderPlacedDomainEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderPlacedDomainEvent(OrderPlacedDomainEvent other) : this() {
      orderId_ = other.orderId_ != null ? other.orderId_.Clone() : null;
      deliveryCost_ = other.deliveryCost_ != null ? other.deliveryCost_.Clone() : null;
      customerDiscount_ = other.customerDiscount_;
      customerId_ = other.customerId_ != null ? other.customerId_.Clone() : null;
      firstName_ = other.firstName_;
      middleName_ = other.middleName_;
      lastName_ = other.lastName_;
      emailAddress_ = other.emailAddress_;
      phoneNumber_ = other.phoneNumber_;
      city_ = other.city_;
      countryCode_ = other.countryCode_;
      postalCode_ = other.postalCode_;
      stateProvince_ = other.stateProvince_;
      streetAddress_ = other.streetAddress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderPlacedDomainEvent Clone() {
      return new OrderPlacedDomainEvent(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private global::VShop.SharedKernel.Infrastructure.Types.Uuid orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VShop.SharedKernel.Infrastructure.Types.Uuid OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "delivery_cost" field.</summary>
    public const int DeliveryCostFieldNumber = 2;
    private global::Google.Type.Money deliveryCost_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Money DeliveryCost {
      get { return deliveryCost_; }
      set {
        deliveryCost_ = value;
      }
    }

    /// <summary>Field number for the "customer_discount" field.</summary>
    public const int CustomerDiscountFieldNumber = 3;
    private int customerDiscount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CustomerDiscount {
      get { return customerDiscount_; }
      set {
        customerDiscount_ = value;
      }
    }

    /// <summary>Field number for the "customer_id" field.</summary>
    public const int CustomerIdFieldNumber = 4;
    private global::VShop.SharedKernel.Infrastructure.Types.Uuid customerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VShop.SharedKernel.Infrastructure.Types.Uuid CustomerId {
      get { return customerId_; }
      set {
        customerId_ = value;
      }
    }

    /// <summary>Field number for the "first_name" field.</summary>
    public const int FirstNameFieldNumber = 5;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "middle_name" field.</summary>
    public const int MiddleNameFieldNumber = 6;
    private string middleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MiddleName {
      get { return middleName_; }
      set {
        middleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_name" field.</summary>
    public const int LastNameFieldNumber = 7;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email_address" field.</summary>
    public const int EmailAddressFieldNumber = 8;
    private string emailAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EmailAddress {
      get { return emailAddress_; }
      set {
        emailAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_number" field.</summary>
    public const int PhoneNumberFieldNumber = 9;
    private string phoneNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PhoneNumber {
      get { return phoneNumber_; }
      set {
        phoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 10;
    private string city_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country_code" field.</summary>
    public const int CountryCodeFieldNumber = 11;
    private string countryCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountryCode {
      get { return countryCode_; }
      set {
        countryCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "postal_code" field.</summary>
    public const int PostalCodeFieldNumber = 12;
    private string postalCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PostalCode {
      get { return postalCode_; }
      set {
        postalCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "state_province" field.</summary>
    public const int StateProvinceFieldNumber = 13;
    private string stateProvince_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StateProvince {
      get { return stateProvince_; }
      set {
        stateProvince_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "street_address" field.</summary>
    public const int StreetAddressFieldNumber = 14;
    private string streetAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StreetAddress {
      get { return streetAddress_; }
      set {
        streetAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderPlacedDomainEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderPlacedDomainEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrderId, other.OrderId)) return false;
      if (!object.Equals(DeliveryCost, other.DeliveryCost)) return false;
      if (CustomerDiscount != other.CustomerDiscount) return false;
      if (!object.Equals(CustomerId, other.CustomerId)) return false;
      if (FirstName != other.FirstName) return false;
      if (MiddleName != other.MiddleName) return false;
      if (LastName != other.LastName) return false;
      if (EmailAddress != other.EmailAddress) return false;
      if (PhoneNumber != other.PhoneNumber) return false;
      if (City != other.City) return false;
      if (CountryCode != other.CountryCode) return false;
      if (PostalCode != other.PostalCode) return false;
      if (StateProvince != other.StateProvince) return false;
      if (StreetAddress != other.StreetAddress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (orderId_ != null) hash ^= OrderId.GetHashCode();
      if (deliveryCost_ != null) hash ^= DeliveryCost.GetHashCode();
      if (CustomerDiscount != 0) hash ^= CustomerDiscount.GetHashCode();
      if (customerId_ != null) hash ^= CustomerId.GetHashCode();
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (MiddleName.Length != 0) hash ^= MiddleName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (EmailAddress.Length != 0) hash ^= EmailAddress.GetHashCode();
      if (PhoneNumber.Length != 0) hash ^= PhoneNumber.GetHashCode();
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (CountryCode.Length != 0) hash ^= CountryCode.GetHashCode();
      if (PostalCode.Length != 0) hash ^= PostalCode.GetHashCode();
      if (StateProvince.Length != 0) hash ^= StateProvince.GetHashCode();
      if (StreetAddress.Length != 0) hash ^= StreetAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (orderId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderId);
      }
      if (deliveryCost_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeliveryCost);
      }
      if (CustomerDiscount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CustomerDiscount);
      }
      if (customerId_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CustomerId);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LastName);
      }
      if (EmailAddress.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(EmailAddress);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PhoneNumber);
      }
      if (City.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(City);
      }
      if (CountryCode.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CountryCode);
      }
      if (PostalCode.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(PostalCode);
      }
      if (StateProvince.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(StateProvince);
      }
      if (StreetAddress.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(StreetAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (orderId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderId);
      }
      if (deliveryCost_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DeliveryCost);
      }
      if (CustomerDiscount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CustomerDiscount);
      }
      if (customerId_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CustomerId);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LastName);
      }
      if (EmailAddress.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(EmailAddress);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PhoneNumber);
      }
      if (City.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(City);
      }
      if (CountryCode.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CountryCode);
      }
      if (PostalCode.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(PostalCode);
      }
      if (StateProvince.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(StateProvince);
      }
      if (StreetAddress.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(StreetAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (orderId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderId);
      }
      if (deliveryCost_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeliveryCost);
      }
      if (CustomerDiscount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CustomerDiscount);
      }
      if (customerId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomerId);
      }
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (MiddleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MiddleName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (EmailAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EmailAddress);
      }
      if (PhoneNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNumber);
      }
      if (City.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (CountryCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountryCode);
      }
      if (PostalCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PostalCode);
      }
      if (StateProvince.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StateProvince);
      }
      if (StreetAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StreetAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderPlacedDomainEvent other) {
      if (other == null) {
        return;
      }
      if (other.orderId_ != null) {
        if (orderId_ == null) {
          OrderId = new global::VShop.SharedKernel.Infrastructure.Types.Uuid();
        }
        OrderId.MergeFrom(other.OrderId);
      }
      if (other.deliveryCost_ != null) {
        if (deliveryCost_ == null) {
          DeliveryCost = new global::Google.Type.Money();
        }
        DeliveryCost.MergeFrom(other.DeliveryCost);
      }
      if (other.CustomerDiscount != 0) {
        CustomerDiscount = other.CustomerDiscount;
      }
      if (other.customerId_ != null) {
        if (customerId_ == null) {
          CustomerId = new global::VShop.SharedKernel.Infrastructure.Types.Uuid();
        }
        CustomerId.MergeFrom(other.CustomerId);
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.MiddleName.Length != 0) {
        MiddleName = other.MiddleName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.EmailAddress.Length != 0) {
        EmailAddress = other.EmailAddress;
      }
      if (other.PhoneNumber.Length != 0) {
        PhoneNumber = other.PhoneNumber;
      }
      if (other.City.Length != 0) {
        City = other.City;
      }
      if (other.CountryCode.Length != 0) {
        CountryCode = other.CountryCode;
      }
      if (other.PostalCode.Length != 0) {
        PostalCode = other.PostalCode;
      }
      if (other.StateProvince.Length != 0) {
        StateProvince = other.StateProvince;
      }
      if (other.StreetAddress.Length != 0) {
        StreetAddress = other.StreetAddress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (orderId_ == null) {
              OrderId = new global::VShop.SharedKernel.Infrastructure.Types.Uuid();
            }
            input.ReadMessage(OrderId);
            break;
          }
          case 18: {
            if (deliveryCost_ == null) {
              DeliveryCost = new global::Google.Type.Money();
            }
            input.ReadMessage(DeliveryCost);
            break;
          }
          case 24: {
            CustomerDiscount = input.ReadInt32();
            break;
          }
          case 34: {
            if (customerId_ == null) {
              CustomerId = new global::VShop.SharedKernel.Infrastructure.Types.Uuid();
            }
            input.ReadMessage(CustomerId);
            break;
          }
          case 42: {
            FirstName = input.ReadString();
            break;
          }
          case 50: {
            MiddleName = input.ReadString();
            break;
          }
          case 58: {
            LastName = input.ReadString();
            break;
          }
          case 66: {
            EmailAddress = input.ReadString();
            break;
          }
          case 74: {
            PhoneNumber = input.ReadString();
            break;
          }
          case 82: {
            City = input.ReadString();
            break;
          }
          case 90: {
            CountryCode = input.ReadString();
            break;
          }
          case 98: {
            PostalCode = input.ReadString();
            break;
          }
          case 106: {
            StateProvince = input.ReadString();
            break;
          }
          case 114: {
            StreetAddress = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (orderId_ == null) {
              OrderId = new global::VShop.SharedKernel.Infrastructure.Types.Uuid();
            }
            input.ReadMessage(OrderId);
            break;
          }
          case 18: {
            if (deliveryCost_ == null) {
              DeliveryCost = new global::Google.Type.Money();
            }
            input.ReadMessage(DeliveryCost);
            break;
          }
          case 24: {
            CustomerDiscount = input.ReadInt32();
            break;
          }
          case 34: {
            if (customerId_ == null) {
              CustomerId = new global::VShop.SharedKernel.Infrastructure.Types.Uuid();
            }
            input.ReadMessage(CustomerId);
            break;
          }
          case 42: {
            FirstName = input.ReadString();
            break;
          }
          case 50: {
            MiddleName = input.ReadString();
            break;
          }
          case 58: {
            LastName = input.ReadString();
            break;
          }
          case 66: {
            EmailAddress = input.ReadString();
            break;
          }
          case 74: {
            PhoneNumber = input.ReadString();
            break;
          }
          case 82: {
            City = input.ReadString();
            break;
          }
          case 90: {
            CountryCode = input.ReadString();
            break;
          }
          case 98: {
            PostalCode = input.ReadString();
            break;
          }
          case 106: {
            StateProvince = input.ReadString();
            break;
          }
          case 114: {
            StreetAddress = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
