// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Modules/Billing/_schemas/Commands/transfer_command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VShop.Modules.Billing.API.Application.Commands {

  /// <summary>Holder for reflection information generated from Modules/Billing/_schemas/Commands/transfer_command.proto</summary>
  public static partial class TransferCommandReflection {

    #region Descriptor
    /// <summary>File descriptor for Modules/Billing/_schemas/Commands/transfer_command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransferCommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhNb2R1bGVzL0JpbGxpbmcvX3NjaGVtYXMvQ29tbWFuZHMvdHJhbnNmZXJf",
            "Y29tbWFuZC5wcm90bxo3U2hhcmVkS2VybmVsL1NoYXJlZEtlcm5lbC5NZXNz",
            "YWdpbmcvX3NjaGVtYXMvdXVpZC5wcm90bxo6U2hhcmVkS2VybmVsL1NoYXJl",
            "ZEtlcm5lbC5NZXNzYWdpbmcvX3NjaGVtYXMvZGVjaW1hbC5wcm90bxofZ29v",
            "Z2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byLbAQoPVHJhbnNmZXJDb21t",
            "YW5kEhcKCG9yZGVyX2lkGAEgASgLMgUuVXVpZBIYCgZhbW91bnQYAiABKAsy",
            "CC5EZWNpbWFsEhQKDGNhcmRfdHlwZV9pZBgDIAEoBRITCgtjYXJkX251bWJl",
            "chgEIAEoCRIcChRjYXJkX3NlY3VyaXR5X251bWJlchgFIAEoCRIXCg9jYXJk",
            "aG9sZGVyX25hbWUYBiABKAkSMwoPY2FyZF9leHBpcmF0aW9uGAcgASgLMhou",
            "Z29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIxqgIuVlNob3AuTW9kdWxlcy5C",
            "aWxsaW5nLkFQSS5BcHBsaWNhdGlvbi5Db21tYW5kc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VShop.SharedKernel.Messaging.CustomTypes.UuidReflection.Descriptor, global::VShop.SharedKernel.Messaging.CustomTypes.DecimalReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VShop.Modules.Billing.API.Application.Commands.TransferCommand), global::VShop.Modules.Billing.API.Application.Commands.TransferCommand.Parser, new[]{ "OrderId", "Amount", "CardTypeId", "CardNumber", "CardSecurityNumber", "CardholderName", "CardExpiration" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TransferCommand : pb::IMessage<TransferCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransferCommand> _parser = new pb::MessageParser<TransferCommand>(() => new TransferCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransferCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VShop.Modules.Billing.API.Application.Commands.TransferCommandReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferCommand(TransferCommand other) : this() {
      orderId_ = other.orderId_ != null ? other.orderId_.Clone() : null;
      amount_ = other.amount_ != null ? other.amount_.Clone() : null;
      cardTypeId_ = other.cardTypeId_;
      cardNumber_ = other.cardNumber_;
      cardSecurityNumber_ = other.cardSecurityNumber_;
      cardholderName_ = other.cardholderName_;
      cardExpiration_ = other.cardExpiration_ != null ? other.cardExpiration_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferCommand Clone() {
      return new TransferCommand(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private global::VShop.SharedKernel.Messaging.CustomTypes.Uuid orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VShop.SharedKernel.Messaging.CustomTypes.Uuid OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 2;
    private global::VShop.SharedKernel.Messaging.CustomTypes.Decimal amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VShop.SharedKernel.Messaging.CustomTypes.Decimal Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    /// <summary>Field number for the "card_type_id" field.</summary>
    public const int CardTypeIdFieldNumber = 3;
    private int cardTypeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CardTypeId {
      get { return cardTypeId_; }
      set {
        cardTypeId_ = value;
      }
    }

    /// <summary>Field number for the "card_number" field.</summary>
    public const int CardNumberFieldNumber = 4;
    private string cardNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CardNumber {
      get { return cardNumber_; }
      set {
        cardNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "card_security_number" field.</summary>
    public const int CardSecurityNumberFieldNumber = 5;
    private string cardSecurityNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CardSecurityNumber {
      get { return cardSecurityNumber_; }
      set {
        cardSecurityNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cardholder_name" field.</summary>
    public const int CardholderNameFieldNumber = 6;
    private string cardholderName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CardholderName {
      get { return cardholderName_; }
      set {
        cardholderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "card_expiration" field.</summary>
    public const int CardExpirationFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp cardExpiration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CardExpiration {
      get { return cardExpiration_; }
      set {
        cardExpiration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransferCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransferCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrderId, other.OrderId)) return false;
      if (!object.Equals(Amount, other.Amount)) return false;
      if (CardTypeId != other.CardTypeId) return false;
      if (CardNumber != other.CardNumber) return false;
      if (CardSecurityNumber != other.CardSecurityNumber) return false;
      if (CardholderName != other.CardholderName) return false;
      if (!object.Equals(CardExpiration, other.CardExpiration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (orderId_ != null) hash ^= OrderId.GetHashCode();
      if (amount_ != null) hash ^= Amount.GetHashCode();
      if (CardTypeId != 0) hash ^= CardTypeId.GetHashCode();
      if (CardNumber.Length != 0) hash ^= CardNumber.GetHashCode();
      if (CardSecurityNumber.Length != 0) hash ^= CardSecurityNumber.GetHashCode();
      if (CardholderName.Length != 0) hash ^= CardholderName.GetHashCode();
      if (cardExpiration_ != null) hash ^= CardExpiration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (orderId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderId);
      }
      if (amount_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Amount);
      }
      if (CardTypeId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CardTypeId);
      }
      if (CardNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CardNumber);
      }
      if (CardSecurityNumber.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CardSecurityNumber);
      }
      if (CardholderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CardholderName);
      }
      if (cardExpiration_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CardExpiration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (orderId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OrderId);
      }
      if (amount_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Amount);
      }
      if (CardTypeId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CardTypeId);
      }
      if (CardNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CardNumber);
      }
      if (CardSecurityNumber.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CardSecurityNumber);
      }
      if (CardholderName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CardholderName);
      }
      if (cardExpiration_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CardExpiration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (orderId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderId);
      }
      if (amount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Amount);
      }
      if (CardTypeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CardTypeId);
      }
      if (CardNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CardNumber);
      }
      if (CardSecurityNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CardSecurityNumber);
      }
      if (CardholderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CardholderName);
      }
      if (cardExpiration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CardExpiration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransferCommand other) {
      if (other == null) {
        return;
      }
      if (other.orderId_ != null) {
        if (orderId_ == null) {
          OrderId = new global::VShop.SharedKernel.Messaging.CustomTypes.Uuid();
        }
        OrderId.MergeFrom(other.OrderId);
      }
      if (other.amount_ != null) {
        if (amount_ == null) {
          Amount = new global::VShop.SharedKernel.Messaging.CustomTypes.Decimal();
        }
        Amount.MergeFrom(other.Amount);
      }
      if (other.CardTypeId != 0) {
        CardTypeId = other.CardTypeId;
      }
      if (other.CardNumber.Length != 0) {
        CardNumber = other.CardNumber;
      }
      if (other.CardSecurityNumber.Length != 0) {
        CardSecurityNumber = other.CardSecurityNumber;
      }
      if (other.CardholderName.Length != 0) {
        CardholderName = other.CardholderName;
      }
      if (other.cardExpiration_ != null) {
        if (cardExpiration_ == null) {
          CardExpiration = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CardExpiration.MergeFrom(other.CardExpiration);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (orderId_ == null) {
              OrderId = new global::VShop.SharedKernel.Messaging.CustomTypes.Uuid();
            }
            input.ReadMessage(OrderId);
            break;
          }
          case 18: {
            if (amount_ == null) {
              Amount = new global::VShop.SharedKernel.Messaging.CustomTypes.Decimal();
            }
            input.ReadMessage(Amount);
            break;
          }
          case 24: {
            CardTypeId = input.ReadInt32();
            break;
          }
          case 34: {
            CardNumber = input.ReadString();
            break;
          }
          case 42: {
            CardSecurityNumber = input.ReadString();
            break;
          }
          case 50: {
            CardholderName = input.ReadString();
            break;
          }
          case 58: {
            if (cardExpiration_ == null) {
              CardExpiration = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CardExpiration);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (orderId_ == null) {
              OrderId = new global::VShop.SharedKernel.Messaging.CustomTypes.Uuid();
            }
            input.ReadMessage(OrderId);
            break;
          }
          case 18: {
            if (amount_ == null) {
              Amount = new global::VShop.SharedKernel.Messaging.CustomTypes.Decimal();
            }
            input.ReadMessage(Amount);
            break;
          }
          case 24: {
            CardTypeId = input.ReadInt32();
            break;
          }
          case 34: {
            CardNumber = input.ReadString();
            break;
          }
          case 42: {
            CardSecurityNumber = input.ReadString();
            break;
          }
          case 50: {
            CardholderName = input.ReadString();
            break;
          }
          case 58: {
            if (cardExpiration_ == null) {
              CardExpiration = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CardExpiration);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
