// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SharedKernel/SharedKernel.Domain/_schemas/gender_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VShop.SharedKernel.Domain.Enums {

  /// <summary>Holder for reflection information generated from SharedKernel/SharedKernel.Domain/_schemas/gender_type.proto</summary>
  public static partial class GenderTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for SharedKernel/SharedKernel.Domain/_schemas/gender_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenderTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjtTaGFyZWRLZXJuZWwvU2hhcmVkS2VybmVsLkRvbWFpbi9fc2NoZW1hcy9n",
            "ZW5kZXJfdHlwZS5wcm90byotCgpHZW5kZXJUeXBlEgoKBkZFTUFMRRAAEggK",
            "BE1BTEUQARIJCgVPVEhFUhACQiKqAh9WU2hvcC5TaGFyZWRLZXJuZWwuRG9t",
            "YWluLkVudW1zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::VShop.SharedKernel.Domain.Enums.GenderType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GenderType {
    [pbr::OriginalName("FEMALE")] Female = 0,
    [pbr::OriginalName("MALE")] Male = 1,
    [pbr::OriginalName("OTHER")] Other = 2,
  }

  #endregion

}

#endregion Designer generated code
